# REFERENCE:
# https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_gcov

dist: bionic

language: cpp

os:
  - linux

compiler:
      - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen


branches:
    only:
        - master


script:
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make
  - ./run-example
  - ./run-test
  - doxygen doxygen.conf

  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local-dir: docs/html
    repo: nkinar/gh-pages
    target-branch: master
