# REFERENCE:
# https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_gcov

dist: bionic

language: cpp

os:
  - linux

compiler:
      - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen

branches:
    only:
        - master

script:
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make
  - ./run-example
  - ./run-test
  - doxygen doxygen.conf

deploy:
    strategy: git
    provider: pages
    cleanup: false
    token: $GITHUB_TOKEN
    local_dir: docs/
    keep_history: true
    on:
        branch: master
