# REFERENCE:
# https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_gcov

dist: bionic

language: cpp

os:
  - linux

compiler:
      - gcc

before_install:
  - sudo apt-get update

branches:
    only:
        - master

script:
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make
  - ./run-example
  - ./run-test
  - doxygen doxygen.conf
